### ISSUE TITLE
rjbcore.so (LoadError)

### ISSUE THREAD

**Issue by svhyd** [arton/rjb#43]
How to fix this error? Thanks for any help.

**The specified module could not be found.   - C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjbcore.so (LoadError)**

```
C:\tmp\rjb-master\rjb-master\test>ruby test.rb
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjb.rb:27: warning: already initialized constant BRIDG
E_FILE
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 126: The specified module could not be f
ound.   - C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjbcore.so (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjb.rb:34:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from test.rb:9:in `rescue in <main>'
        from test.rb:5:in `<main>'
```

```
C:\tmp\rjb-master\rjb-master\test>ruby -v
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
```

**Comment by arton** [comment]
Hi
It seems that you did not install Rjb correctly. Therefore there is no rjbcore.so. It's a DLL that shoud be compiled at install time.

**Comment by svhyd** [comment]
What am I doing wrong here? I downloaded the gem and installed it. It did not complain about anything during installation.

----------
```
c:\Ruby193\bin>gem install c:\tmp\rjb-1.4.7-x86-mswin32-100.gem
Successfully installed rjb-1.4.7-x86-mswin32-100
1 gem installed
Installing ri documentation for rjb-1.4.7-x86-mswin32-100...
Installing RDoc documentation for rjb-1.4.7-x86-mswin32-100...

```
```
C:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.4.7-x86-mswin32-100\test>gem list rjb

*** LOCAL GEMS ***

rjb (1.4.7 x86-mswin32-100)

```
```
C:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.4.7-x86-mswin32-100\test>ruby test.rb
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjb.rb:27: warning: already initialized constant BRIDG
E_FILE
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 126: The specified module could not be f
ound.   - C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjbcore.so (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.7-x86-mswin32-100/lib/rjb.rb:34:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from test.rb:9:in `rescue in <main>'
        from test.rb:5:in `<main>'
```

**Comment by arton** [comment]
I wonder if you could show me the result of

dir C:\Ruby193\lib\ruby\gems\1.9.1\gems
dir C:\ruby193\lib\ruby\site_ruby\1.9.1
dir C:\ruby193\lib\ruby\vendor_ruby\1.9.1
dir c:\windows\system32\msvcr*.dll

I doubt there are another Rjb instance, because of the log "warning: already initialized constant BRIDG
E_FILE".
And the possible cause of LoadError are: 1. no rjbcore.so or lack of MSVCR100.dll (because the gem is marked -mswin32-100).
If you have no MSVCR100.dll, the visit microsoft download center and get and install it.
Or if you installed another copy of Rjb gem or naked lib, should delete them.

Regards

**Comment by svhyd** [comment]
```
C:\Ruby193\bin>dir c:\windows\system32\msvcr*.dll
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of c:\windows\system32

06/11/2011  02:15 AM           829,264 msvcr100.dll
09/11/2013  07:39 PM            18,000 msvcr100_clr0400.dll
09/11/2013  07:39 PM           855,664 msvcr110_clr0400.dll
10/04/2013  11:58 PM           963,232 msvcr120.dll
10/13/2015  02:22 AM           869,568 msvcr120_clr0400.dll
12/16/2011  04:46 AM           634,880 msvcrt.dll
               6 File(s)      4,170,608 bytes
               0 Dir(s)  29,074,812,928 bytes free
```


```
C:\Ruby193\bin>dir C:\Ruby193\lib\ruby\gems\1.9.1\gems
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of C:\Ruby193\lib\ruby\gems\1.9.1\gems

03/15/2016  11:54 AM    <DIR>          .
03/15/2016  11:54 AM    <DIR>          ..
03/14/2016  08:51 PM    <DIR>          actionmailer-2.3.4
03/14/2016  08:51 PM    <DIR>          actionpack-2.3.4
03/14/2016  08:51 PM    <DIR>          activerecord-2.3.4
03/14/2016  08:51 PM    <DIR>          activeresource-2.3.4
03/14/2016  08:51 PM    <DIR>          activesupport-2.3.4
03/14/2016  08:55 PM    <DIR>          cgi_multipart_eof_fix-2.5.0
03/14/2016  08:55 PM    <DIR>          gem_plugin-0.2.3
03/14/2016  09:48 PM    <DIR>          hoe-3.14.2
03/14/2016  08:56 PM    <DIR>          httpclient-2.7.1
03/14/2016  09:08 PM    <DIR>          mongrel-1.2.0.pre2-x86-mswin32
03/14/2016  09:03 PM    <DIR>          needle-1.3.0
03/14/2016  08:59 PM    <DIR>          net-sftp-2.0.1
03/14/2016  08:59 PM    <DIR>          net-ssh-2.0.4
03/14/2016  09:49 PM    <DIR>          netaddr-1.5.1
03/14/2016  09:48 PM    <DIR>          paginator-1.1.1
03/14/2016  09:04 PM    <DIR>          pg-0.18.4-x86-mingw32
03/14/2016  08:51 PM    <DIR>          rack-1.0.1
03/14/2016  08:51 PM    <DIR>          rails-2.3.4
03/14/2016  08:40 PM    <DIR>          rake-0.9.2.2
03/14/2016  08:40 PM    <DIR>          rdoc-3.9.5
03/15/2016  11:53 AM    <DIR>          rjb-1.3.8-x86-mswin32-60
03/15/2016  11:54 AM    <DIR>          rjb-1.4.7-x86-mswin32-100
               0 File(s)              0 bytes
              24 Dir(s)  29,076,717,568 bytes free
```

```
C:\Ruby193\bin>dir C:\ruby193\lib\ruby\site_ruby\1.9.1
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of C:\ruby193\lib\ruby\site_ruby\1.9.1

03/14/2016  08:40 PM    <DIR>          .
03/14/2016  08:40 PM    <DIR>          ..
11/15/2014  12:28 AM             1,415 gauntlet_rubygems.rb
03/14/2016  08:40 PM    <DIR>          i386-msvcrt
11/15/2014  12:28 AM               847 rb-readline.rb
03/14/2016  08:40 PM    <DIR>          rbconfig
11/15/2014  12:28 AM           274,182 rbreadline.rb
11/15/2014  12:28 AM            13,262 readline.rb
03/14/2016  08:40 PM    <DIR>          rubygems
11/15/2014  12:28 AM            34,951 rubygems.rb
11/15/2014  12:28 AM               268 ubygems.rb
               6 File(s)        324,925 bytes
               5 Dir(s)  29,076,783,104 bytes free

```

```
C:\Ruby193\bin>dir C:\ruby193\lib\ruby\site_ruby\1.9.1
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of C:\ruby193\lib\ruby\site_ruby\1.9.1

03/14/2016  08:40 PM    <DIR>          .
03/14/2016  08:40 PM    <DIR>          ..
11/15/2014  12:28 AM             1,415 gauntlet_rubygems.rb
03/14/2016  08:40 PM    <DIR>          i386-msvcrt
11/15/2014  12:28 AM               847 rb-readline.rb
03/14/2016  08:40 PM    <DIR>          rbconfig
11/15/2014  12:28 AM           274,182 rbreadline.rb
11/15/2014  12:28 AM            13,262 readline.rb
03/14/2016  08:40 PM    <DIR>          rubygems
11/15/2014  12:28 AM            34,951 rubygems.rb
11/15/2014  12:28 AM               268 ubygems.rb
               6 File(s)        324,925 bytes
               5 Dir(s)  29,076,783,104 bytes free

C:\Ruby193\bin>dir C:\ruby193\lib\ruby\vendor_ruby\1.9.1
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of C:\ruby193\lib\ruby\vendor_ruby\1.9.1

03/14/2016  08:40 PM    <DIR>          .
03/14/2016  08:40 PM    <DIR>          ..
03/14/2016  08:40 PM    <DIR>          i386-msvcrt
               0 File(s)              0 bytes
               3 Dir(s)  29,059,559,424 bytes free

```

![image](https://cloud.githubusercontent.com/assets/516459/13790681/127fa8b0-eac0-11e5-8e64-383b9b66fced.png)

![image](https://cloud.githubusercontent.com/assets/516459/13790697/2385051a-eac0-11e5-9615-83677f134af4.png)

**Comment by svhyd** [comment]
In my Ruby 1.8.7 installation at least it seems to load fine. However, looks like I'm getting an iconv error.

```
C:\ruby-187-72\lib\ruby\gems\1.8\gems\rjb-1.3.8-x86-mswin32-60\test>ruby test.rb
start RJB(1.3.8) test
Loaded suite test
Started
.....................................E..................
Finished in 1.765 seconds.

  1) Error:
test_kjconv(TestRjb):
Iconv::IllegalSequence: "┬╗├║┬Ñ├å┬Ñ┬¡┬Ñ┬╣"...
    test.rb:181:in `iconv'
    test.rb:181:in `method_missing'
    test.rb:181:in `test_kjconv'

56 tests, 171 assertions, 0 failures, 1 errors
```

**Comment by svhyd** [comment]
RJB lib directory under Ruby 1.9.3 lists the rjbcore.so fine. Is this expected or unexpected?

```
c:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.3.8-x86-mswin32-60\lib>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 96EF-A362

 Directory of c:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.3.8-x86-mswin32-60\lib

03/16/2016  07:53 PM    <DIR>          .
03/16/2016  07:53 PM    <DIR>          ..
03/16/2016  07:53 PM             2,155 rjb.rb
03/16/2016  07:53 PM            57,406 rjbcore.so
03/16/2016  07:53 PM             3,780 rjbextension.rb
               3 File(s)         63,341 bytes
               2 Dir(s)  33,868,926,976 bytes free
```

**Comment by arton** [comment]
Hi
Thank you for your report.
The answer of your last question is 'yes', if your ruby is built by msvc 100 == VC 2010.
I wonder if you could show me console output of 'ruby -d test.rb' by your failed test.
   may: C:\tmp\rjb-master\rjb-master\test>ruby -d test.rb
Regards

**Comment by svhyd** [comment]
Hi, here's the output of what you asked for:

```
c:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.3.8-x86-mswin32-60\test>ruby -d test.rb
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1273 - cannot load such file -- rubygems/defaul
ts/ruby
test.rb:497: warning: assigned but unused variable - method
test.rb:540: warning: assigned but unused variable - s
test.rb:702: warning: assigned but unused variable - sig
test.rb:771: warning: ambiguous first argument; put parentheses or even spaces
test.rb:785: warning: ambiguous first argument; put parentheses or even spaces
test.rb:799: warning: assigned but unused variable - e
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36 - cannot load such file -- rj
b
Exception `LoadError' at c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so - incompatible libr
ary version - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - incompatible library versio
n - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so
c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjb.rb:14: warning: already initialized constant BRIDGE
_FILE
Exception `LoadError' at c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so - incompatible libr
ary version - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - incompatible library versio
n - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - incompatible library versio
n - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so
c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': incompatible library version - c:/Ruby19
3/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjbcore.so (LoadError)
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.3.8-x86-mswin32-60/lib/rjb.rb:21:in `<top (required)>'
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from test.rb:9:in `rescue in <main>'
        from test.rb:5:in `<main>'
```

**Comment by svhyd** [comment]
This output is with rjb-1.4.9-x86-mswin32-**100** and Ruby 1.9.3:

```
c:\Ruby193\lib\ruby\gems\1.9.1\gems\rjb-1.4.9-x86-mswin32-100\test>ruby -d test.rb
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1273 - cannot load such file -- rubygems/defaul
ts/ruby
test.rb:497: warning: assigned but unused variable - method
test.rb:540: warning: assigned but unused variable - s
test.rb:702: warning: assigned but unused variable - sig
test.rb:771: warning: ambiguous first argument; put parentheses or even spaces
test.rb:785: warning: ambiguous first argument; put parentheses or even spaces
test.rb:799: warning: assigned but unused variable - e
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36 - cannot load such file -- rj
b
Exception `LoadError' at c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so - 126: The specifi
ed module could not be found.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - 126: The specified module c
ould not be found.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so
c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjb.rb:27: warning: already initialized constant BRIDG
E_FILE
Exception `LoadError' at c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so - 126: The specifi
ed module could not be found.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - 126: The specified module c
ould not be found.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so
Exception `LoadError' at c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:63 - 126: The specified module c
ould not be found.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so
c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 126: The specified module could not be f
ound.   - c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjbcore.so (LoadError)
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/rjb-1.4.9-x86-mswin32-100/lib/rjb.rb:34:in `<top (required)>'
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from test.rb:9:in `rescue in <main>'
        from test.rb:5:in `<main>'

```

**Comment by arton** [comment]
Thank you for your cooperation.
I suppose that your 1.9.1 lacks iconv or dl.
Can you run ruby as 'ruby -rdl -e "p DL" ' ? If not, you should get DL.so for loading rjb.
If calling DL was succeeded, then, I wonder if you could check it with 'ruby -riconv -e "p Iconv" '. 
If it was failed, iconv is not important as DL, then you may put fake iconv.rb in your site_ruby directory.
---cut from below line----
# fake iconv
ICONV = nil
---cut to above line, and put it in your site_ruby/1.9.1/iconv.rb

Regards.

**Comment by arton** [comment]
Hi,
I found that your 1.8.7 is mswin32 as rjb.
> ruby 1.8.7 (2008-08-11 patchlevel 72) [i386-mswin32]
However your 1.9.3 is mingw32. 
> ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
I think you should use i386-mswin32-100 ruby for working with rjb-*-x86-mswin32-100.
Because mingw32 is different architecture from mswin32.
 (Indeed, I'm not sure, because I don't have any interest of mingw).

Regards.
