### ISSUE TITLE
Error: test_inner_exception(TestRjb): NameError: uninitialized constant TestRjb::IllegalStateException

### ISSUE THREAD

**Issue by aneilbaboo** [arton/rjb#48]
I'm getting this failure when I run the test.rb script on macOS Sierra (10.12) and jdk1.8.0_71:
```
$ ruby test.rb 
start RJB(1.5.4) test
Loaded suite test
Started
...................................E
============================================================================================
Error: test_inner_exception(TestRjb): NameError: uninitialized constant TestRjb::IllegalStateException
test.rb:819:in `rescue in test_inner_exception'
test.rb:816:in `test_inner_exception'
     813: 
     814:   def test_inner_exception
     815:     test = import('jp.co.infoseek.hp.arton.rjb.Test').new
  => 816:     begin
     817:       test.cause_exception
     818:       flunk("no exception")
     819:     rescue IllegalStateException => e
============================================================================================
..............................

Finished in 0.428781 seconds.
--------------------------------------------------------------------------------------------
66 tests, 219 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
98.4848% passed
--------------------------------------------------------------------------------------------
153.92 tests/s, 510.75 assertions/s

```

**Comment by arton** [comment]
This was caused by old jp.co.infoseek.hp.arton.rjb.Test.class.
At this time, I have no JDK5 (the oldest support version). Therefore I can't update the class.
If you would like to pass all tests, I wonder if you could compile Test.java by yourself and replace the class file that sits in test/jp/co/infoseek/hp/arton/rjb with it.

**Comment by arton** [comment]
fixed
