### ISSUE TITLE
respond_to? method of Exception object always returns true since rjb 1.5.9.

### ISSUE THREAD

**Issue by buzztaiki** [arton/rjb#71]
I expect that `respond_to?` will return false when method does not exist.
Standard object seems to be fine.

## Test script:

```ruby
require 'rjb'

def java_exception
  Rjb.import('java.lang.Integer').parseInt('XXX')
rescue StandardError => e
  e
else
  raise 'java exception not thrown'
end

puts Rjb::VERSION

puts Rjb.import('java.lang.String').new('XXX').respond_to? :unknown_method

e = java_exception
puts e.respond_to? :unknown_method
e.unknown_method if e.respond_to? :unknown_method
```

## rjb 1.6.0
```
1.6.0
false
true
Traceback (most recent call last):
        2: from test.rb:19:in `<main>'
        1: from test.rb:19:in `method_missing'
test.rb:19:in `method_missing': Fail: unknown method name `unknown_method' (RuntimeError)
```

## rjb 1.5.9
```
bundle exec ruby test.rb
1.5.9
false
true
Traceback (most recent call last):
        2: from test.rb:19:in `<main>'
        1: from test.rb:19:in `method_missing'
test.rb:19:in `method_missing': Fail: unknown method name `unknown_method' (RuntimeError)
```

## rjb 1.5.8
```
bundle exec ruby test.rb
1.5.8
false
false
```

**Comment by arton** [comment]
Hi
Thank you for the report.
Indeed I didn't implement respond_to? and 1.6.1 now fully supports it.

**Comment by buzztaiki** [comment]
Super fast! Thank you for your fix!

**Comment by akiotajima** [comment]
@buzztaiki Hi, would you please close this issue?

**Comment by buzztaiki** [comment]
Sorry, I forgot to close it.
