### ISSUE TITLE
Crash: illegal hardware instruction when used inside Ruby Fiber

### ISSUE THREAD

**Issue by bmulholland** [arton/rjb#87]
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

test.rb
```
require "rjb"

Fiber.new {
  Rjb.import("java.lang.String")
}.resume
```

> % ruby test.rb
> [1]    1453 illegal hardware instruction  ruby test.rb

**Comment by bmulholland** [comment]
Alternatively:

```
require "rjb"

Rjb.load # ADDED

Fiber.new {
  Rjb.import("java.lang.String")
}.resume

```

> % ruby test.rb
> test.rb:9:in `import': unknown exception (RuntimeError)
>	from test.rb:9:in `block in <main>'

**Comment by bmulholland** [comment]
If it makes a difference in choosing with of the three issues I've filed to look into first, this one is my top priority -- it's blocking me from using [GraphQL Dataloader](https://graphql-ruby.org/dataloader/overview.html) to improve the performance of my app.

**Comment by arton** [comment]
Hi bmulholland
I could reproduce the crash on x64 box. Therefore it should be fiber and rjb (jvm initialization including class load) combination.

I think it's critical issue between Ruby-Rjb-JVM and I suppose the fix is the long way travel.
I wonder if you could change your code such as
```
Rjb.load
JString = Rjb.import('java.lang.String')  # import classes from the main thread 
Fiber.new {
  # invoke JString...
}
...
```

**Comment by bmulholland** [comment]
Thanks for your investigation. We'll look into alternative approaches.
