### ISSUE TITLE
[!] rjb cannot be installed and run on windows

### ISSUE THREAD

**Issue by winezer0** [arton/rjb#95]
OS:   windows 10 
Lang:  Chinese

# BUG 1：
In a Chinese Env, the 'javah -version' invoked by the rjb installation cannot be matched with a normal RE, indicating an encoding error
```
javah -version
javah版本 "1.8.0_261"
```
BUG1 Cause:：rjb/ext/extconf.rb does not support Chinese encoding matching, please modify the code.

![image](https://github.com/arton/rjb/assets/46115146/0da22aca-a6eb-4eda-8a18-28960707091e)

Temporary fix for BUG1：Change the language of the OS to english.

# BUG 2: 
After installing rjb with a temporary fix, every time you run the program:
```
[!] Partially dependent java plugins cannot be used normally
```

**Comment by winezer0** [comment]
Please help me deal with this problem, thank you very much

**Comment by arton** [comment]
@winezer0 Sorry for the late response. I'll fix it asap.

**Comment by arton** [comment]
Hi @winezer0, I can't reproduce this issue, I wonder if you could attach or copy&paste the extconf.rb output.

**Comment by winezer0** [comment]
![image](https://github.com/arton/rjb/assets/46115146/f8207e49-d664-4346-b0a0-d90107411acb)

**Comment by winezer0** [comment]
RuntimeError: can't create Java VM  
 
 How should we deal with this issue? It seems to me that the issue of history has not been dealt with, is it impossible to solve it

**Comment by winezer0** [comment]
```
rjb>cd test

rjb\test>ruby test.rb
start RJB(1.6.9) test
Loaded suite test
Started
E
========================================================================================================================Error: test_64fixnum(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_CallByNullForArrays(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_CastObjectArray(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_add_jar(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_add_jars(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_anoninterface(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_array(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_array_of_arrays(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_auto_constructor_selection(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_auto_conv(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_bothdirection_buffer(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_bothdirection_chararray(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_bytearg(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_capitalized_method(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_class_methods_extension(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_class_pmethods_extension(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_combination_charcters(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_comparator(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_constants(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_enum(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_exception(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_extend(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_extend_with_factory(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_failed_constructor_call(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_fetch_ctor_signature(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_fetch_method_signature(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_fetch_method_without_signature(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_fetch_static_method_signature(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_field(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_fornamehook(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_generics_map(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_impl(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_import_and_instanciate(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_importobj(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_importobjarray(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_inner_exception(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_instance_throw(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_instancefield_from_class(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_instancemethod_from_class(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_java_class_methods(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_java_hangul_syllable(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_java_methods(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_java_utf8(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_kjconv(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_longarg(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_longcallback(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_metaclass(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_method_otherthan_bound(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_methods_extension(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_newobject(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_noarg_invoke(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_noarg_sinvoke(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_null_string(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_obj_to_primitive(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_passingclass(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_pmethods_extension(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_primitive_to_obj(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_re_raise(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_reraise_exception(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_respond_to(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_rubyize(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_scalar(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_send_array_of_arrays(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_static_derived_method(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_throw(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_throw_clear(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_throw_error(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_typedarray(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_unbind(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================E
========================================================================================================================Error: test_underscored_constant(TestRjb): RuntimeError: can't create Java VM
test.rb:21:in `load'
test.rb:21:in `setup'
========================================================================================================================
Finished in 0.399002 seconds.
------------------------------------------------------------------------------------------------------------------------70 tests, 0 assertions, 0 failures, 70 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
------------------------------------------------------------------------------------------------------------------------175.44 tests/s, 0.00 assertions/s

```

**Comment by winezer0** [comment]
wait for your

**Comment by winezer0** [comment]
I will test in windows environment, please wait

**Comment by winezer0** [comment]
Very good, thank you very much,

now  rjb is running successfully on windows
